version: '3.8'
services:
  backend:
    build:
      context: ./final_be
    ports:
      - '4000:4000'
    volumes:
      - ./final_be:/usr/src/app
      - /usr/src/app/node_modules # 로컬 `node_modules`를 덮어쓰지 않도록 설정
    environment:
      - NODE_ENV=development
    restart: always

  frontend:
    build:
      context: ./final_fe
    ports:
      - '3000:3000'
    volumes:
      - ./final_fe:/usr/src/app
      - /usr/src/app/node_modules # 로컬 `node_modules`를 덮어쓰지 않도록 설정
    environment:
      - NODE_ENV=development
    restart: always

  admin:
    build:
      context: ./final_admin
    ports:
      - '3001:3001'
    volumes:
      - ./final_admin:/usr/src/app
      - /usr/src/app/node_modules # 로컬 `node_modules`를 덮어쓰지 않도록 설정
    environment:
      - NODE_ENV=development
    restart: always
